CREATE DATABASE LMS;
USE LMS;

-- MEMBUAT TABEL DAFTAR USER
CREATE TABLE daftar_user(
ID_USER INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
U_NAME VARCHAR (50) NOT NULL ,
TGL_LAHIR DATE,
PEKERJAAN VARCHAR (50),
ALAMAT VARCHAR (100)
);

-- MEMBUAT TABEL DAFTAR BUKU
CREATE TABLE daftar_buku(
ID_BUKU VARCHAR(50) NOT NULL PRIMARY KEY,
NAMA_BUKU VARCHAR (100) NOT NULL ,
KATEGORI VARCHAR(50),
STOCK INT
);

INSERT INTO daftar_buku(ID_BUKU,NAMA_BUKU,KATEGORI,STOCK) VALUES
('1000','KPI A to Z','Business','5'),
('2000','Python for Dummy','Programming','10'),
('3000','Harry Potter : The Deathly Hallows','Fiction','4'),
('1001','Even Elephant Can Dance','Business','3'),
('3001','Tuesday With Morries','Fiction','4');

SELECT * FROM daftar_buku WHERE NAMA_BUKU OR KATEGORI LIKE '%business%';


-- MEMBUAT DAFTAR PEMINJAMAN
CREATE TABLE daftar_pinjam(
ID_PINJAM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_USER INT NOT NULL,
ID_BUKU VARCHAR(50),
NAMA_USER VARCHAR(50),
NAMA_BUKU VARCHAR(100),
TANGGAL_PINJAM DATE,
TANGGAL_PENGEMBALIAN DATE,
FOREIGN KEY (ID_USER) REFERENCES daftar_user(ID_USER),
FOREIGN KEY (ID_BUKU) REFERENCES daftar_buku(ID_BUKU)
); 

 
